### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by staticfloat** [JuliaCI/julia-buildkite-plugin#10]
@maleadt how do we tag a new release?  I want to use the `curl` versions without specifying a git hash

**Comment by maleadt** [comment]
Did you already create a v1.2 tag 6 days ago, or is the GitHub UI confusing?
It has automatically created v1 then, so everything was basically set up already: https://github.com/JuliaCI/julia-buildkite-plugin/releases/tag/v1

**Comment by staticfloat** [comment]
Oh!  I didn't realize.  That's weird though, because when I run pipelines right now with `julia#v1` it doesn't seem to contain the new commits?

**Comment by staticfloat** [comment]
example: https://buildkite.com/julia-computing-1/fmus-dot-jl/builds/5#_

**Comment by maleadt** [comment]
Maybe try restarting the agent?

**Comment by staticfloat** [comment]
I sent an email to buildkite support (CC'ing you).  It looks like BK never updates its cache of git tags, even after you restart it.

**Comment by DilumAluthge** [comment]
> It looks like BK never updates its cache of git tags, even after you restart it.

😬 That is not great. I was so pleased with the auto-updated `v1` tag that Tim set up.

**Comment by maleadt** [comment]
Ah, that sucks. Doesn't look like they'll change that behavior soon either :slightly_frowning_face:

I think I don't run into that because I not only restart the agent for every job, but completely restart the container it's running in. I want to do that so that builds run in a well-defined environment (except for a shared home folder, of course, ref https://github.com/JuliaCI/julia-buildkite-plugin/issues/9). For example this build looks like it does a full clone of the plugins, https://buildkite.com/julialang/cuda-dot-jl/builds/1226#90d456d6-8c62-4bf7-b5a9-47668d873ac2, and because it ends up in `/etc/buildkite-agent/plugins` it gets wiped when the agent restarts.

Maybe you can switch to such a set-up too, or alternatively use an global environment hook (which runs before the plugin checkout) to update those repositories in `/etc/buildkite-agent/plugins`?

**Comment by staticfloat** [comment]
The agent restarting technique should work well anywhere we're running inside of Docker, where it's super cheap to throw away the accumulated state.  But I worry that I'm going to want to run Windows CI and MacOS CI and whatnot for some projects, and there it won't be as easy to just use the "docker restart" trick.

So perhaps a global environment hook is the right way to go; where we can walk over the plugins and forcibly pull all tags.

**Comment by staticfloat** [comment]
I've got a workaround deployed in our environment hooks, I've documented it [here](https://github.com/buildkite/agent/issues/422#issuecomment-814596245), so I think we're in a good place now.
